config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
    
    resources :books, only: [:index,:create,:destroy]
    ## multi lang desteği için 
    scope "/:locale" do
        resources :products do
            post 'gift/:id', to: "products#gift_send", as: "gift_send"
        end
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :variants, dependent: :destroy
    #% has_one_attached ile resim tablosuyla bağlantı verdik. image ile ulaşım sağladık. ( product.image )
    has_many_attached :images

    accepts_nested_attributes_for :variants

    validates :name, presence: true, length: {minimum:3}

    ## Link yapısını 1-kemal-aydin yaptık, parametirize bizim için slug yapısı oluşturuyoru
    def to_param
        "#{id}-#{name.parameterize}"
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product

  # @param email 
  def send_gift (email)
    #% Mail Gönderme aksiyonunu ateşleme (Deliver_later komutu ile jobs tanımlanıyor);
    GiftMailer.with(product: product,email: email).send_gift.deliver_later if decrement!(:stock)
    puts "Mail Sending for #{email}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!
    ## multi lang desteği
    def default_url_options
        { locale: I18n.locale }
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    skip_before_action :authenticate_user!

    def index
        @books = Book.all
        @book = Book.new
    end

    def create
        puts params[:book]
        @book = Book.new(book_params)
        respond_to do |format|
            if @book.save
                format.js
                format.json { render json: @book, status: :created, location: @book }
            else
                format.json { render json: @book.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @book = Book.find(params[:id]).destroy
    end

    private
    def book_params
        params.require(:book).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    before_action :find_product, only: [:show, :edit, :update]
    before_action :set_locale
    skip_before_action :authenticate_user!, only: [:index,:show]

    #% form yapımdan dolayı authenticity_token birden fazla basıylıyor. önüne geçmek için
    #% skip_before_action :verify_authenticity_token tanımlayarak kaçmasını sağlıyoruz.
    skip_before_action :verify_authenticity_token, only: [:gift_send]

 
    def set_locale
        I18n.locale = params[:locale] || I18n.default_locale
    end

    def index
        @products = Product.all
    end

    def show
    end

    def new
        @product = Product.new
        @product.variants.build

    end

    def create
        @product = Product.new(product_params)
        if(@product.save)
            redirect_to product_path(@product)
            flash[:message] = ["status" => "success", "message" => "New Product Create Successfull"]
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if(@product.update(product_params))
            flash[:message] = ["status" => "info", "message" => "Product updated"]
            redirect_to product_path(@product)
        else
            render 'edit'
        end
    end
    
    def gift_send
        @product = Product.find(params[:product_id])
        @variant = @product.variants.find(params[:id])
        unless(@variant.stock.positive?)
            # TODO: with %w() 
            flash[:message] = ['status' => 'danger','message' => 'Tshirt stock not aviable']
            redirect_to product_path(@product)
        else
            #* refactor edildi, böylece direkt model üzerinden ulaşarak -1 yapabiliyoruz.
            @variant.send_gift(params[:email])
            flash[:message] = ["status" => "success", "message" => "The product will be sent to your friend"]
            redirect_to product_path(@product)
        end
    end

    def destroy
        @product = Product.find(params[:id]).destroy
        flash[:message] = ["status" => "info", "message" => "Product deleted"]
        redirect_to products_path()
    end


    private
    def product_params
        #% image değişkeni de eklenerek upload sistemi dahil edildi.
        params.require(:product).permit(:name,:price,:description, images:[], variants_attributes: [:id,:name,:stock])
    end

    def update_stock (data,decrease_stock)
        data.stock - decrease_stock
    end

    def find_product
        @product = Product.includes(:variants).find(params[:id])
    end

end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
    def default_currency
        "₺"
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/books/_book.html.erb
<li id="<%= dom_id book %>">
    <%= book.name %>
    <%= link_to "[x]", book_path(book), method: :delete, data: { remote: true, confirm: "Emin misin ? " } %>
</li>

app/views/books/create.js.erb
$("<%= escape_javascript(render @book) %>").appendTo("#books");
alert("Book added")
document.getElementById("book_form").reset();

app/views/books/destroy.js.erb
$('#book_<%= @book.id %>').remove();

app/views/books/index.html.erb
<div style="clearfix"></div><br>

<%= form_with(model: @book, id: "book_form") do |f| %>
   <%= f.label :name %><br>
   <%= f.text_field :name %>
   <%= f.submit nil, class:"btn btn-info" %>
<% end %>
<br>

<ul id="books">
    <%= render(@books) %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ders2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if(notice) %>
      <div class="notice alert alert-info"><%= notice %></div>
    <% end %>
    <% if(alert) %>
      <div class="alert alert alert-danger"><%= alert %></div>
    <% end%>
    <div style="margin-top:15px;"></div>
  <div class="container">
    <div class="col-md-12">
    <div class="pull-right col-md-12" style="text-align: right">
      <% unless(user_signed_in?) %>
        <%= link_to "Login", new_user_session_path(), class:'btn btn-primary' %>
        <%= link_to "Register", new_user_registration_path(), class:'btn btn-info' %>
      <% else%>
        Welcome, <strong><%= current_user.email %></strong>
        <%= link_to "Home", products_path(), class: 'btn btn-info btn-sm'  %>
        <%= link_to "My Profile", edit_user_registration_path(), class: 'btn btn-primary btn-sm' if user_signed_in?  %>
        <%= link_to "Logout", destroy_user_session_path(), class: 'btn btn-danger btn-sm', method: :delete  if user_signed_in?  %>

      <% end %>
    </div>
    <div class="col-md-12" style="float:left">
      <% if(flash[:message]) %>
        <% flash[:message].each do |data| %>
            <div class="alert alert-<%= data['status'] %>"> <%= data['message'] %> </div>
        <% end %>
        <% end %>
      <%= yield %>
    </div>
    <div class="clearfix"><br></div>
    </div>
  </div>
  </body>
</html>

app/views/products/_form.html.erb
 <% if @product.errors.any? %>
  <div class="alert alert-danger">
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  

<%= form_with model: @product , multiple: true, local: true do |form| %>
<div class="col-md-6" style="float:left;">
    <h3>Product</h3>
    <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name,class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :price %>
        <%= form.text_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :description %>  
        <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :image %>
        <%= form.file_field :images, :multiple => true, class: "form-control" %>
    </div>
</div>
<div class="col-md-6" style="float:left">
    <h3>Variants</h3>
    <%= form.fields_for :variants do |variants_form| %>
    <div class="form-group">
        <%= variants_form.label 'Variants Name' %>
        <%= variants_form.text_field :name,class: "form-control" %>
    </div>
    <div class="form-group">
        <%= variants_form.label :stock %>
        <%= variants_form.text_field :stock, class: "form-control" %>
    </div>
    <hr>
    <% end %>
    <div class="form-group">
        <%= form.submit nil, class: "btn btn-success", style: "float:right" %>
    </div>
</div>
<div class="clearfix"></div>
<% end %>

app/views/products/_product.html.erb
<tr>
    <td>
    <%= link_to product_path(product) do %>
        <%= product.name %>
    <% end %>
    </td>
    <%# Default currency tanımladık, helper klasöründe application_helper içerisinde %>
    <td><%= product.price %> <%= default_currency %></td>
    <td><%= product.description %></td>
    <td>
        <%= link_to  'Edit', edit_product_path(product), class: 'btn btn-warning btn-sm' %>
        <%= link_to  'Delete', product_path(product), method: :delete, data: { confirm: "Silmek İstediğinize Emin misiniz ? " }, class: 'btn btn-danger btn-sm' %>
    </td>
</tr>

app/views/products/edit.html.erb
<h1> Edit Product : <%= @product.name %> </h1>

<p>
    <%= link_to  "Back", :back, class: "btn btn-primary btn-sm" %>
</p>

<%= render 'form' %>

app/views/products/index.html.erb
<h1> <%= t('products') %> </h1>

<p>
    <%= link_to "New Product", new_product_path(), class: 'btn btn-primary' %>
</p>

<table class="table table-bordered table-hover">
    <thead>
        <tr>  
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th style="width: 135px; text-align:center"></th>
        </tr>
    </thead>
    <%= render(@products) %>
</table>

app/views/products/new.html.erb
<h1> New Product </h1>
<p>
    <%= link_to "Back", :back, class: "btn btn-primary btn-sm" %>
</p>

<%= render 'form' %>

app/views/products/show.html.erb
<h1> <%= @product.name %></h1>
<p>
    <%= link_to  "Back", products_path(), class: "btn btn-primary btn-sm" %>
    <%= link_to  "Edit", edit_product_path(@product), class: "btn btn-warning btn-sm" %>
</p>

<p>
    <strong> Product Name : </strong> <%= @product.name %>
</p>

<p>
    <strong> Product Price : </strong> <%= @product.price %> TL
</p>

<p>
    <strong> Product Description : </strong> <%= @product.description %>
</p>

<p>
    <strong> Product Images : </strong> 
    <% if(@product.images.attached?) %>
        <% @product.images.each do |image| %>
            <%= image_tag image, size: '200' %>
        <% end %>
    <% else %>
        <div class="alert alert-info">Image not found for this product</div>
    <% end %>
</p>
<hr>
<h2>Variants</h2>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Stock</th>
            <th>Sending Mail</th>
            <th style="width: 50px"></th>
        </tr>
    </thead>
    <tbody>
    <% if(@product.variants.any?) %>
        <%= render partial: 'variants/select_variant', locals: { product: @product }  %>
    <% end %>
    </tbody>
</table>

app/views/variants/_select_variant.html.erb
<% product.variants.each do |variant| %>
    <%= form_tag(product_gift_send_path(@product,variant), method: "post", id:"form_#{variant.id}") do %>
    <tr 
        <% if(variant.stock < 1) %>
            class="table-danger"
        <% end %>
        >
        <td><%= variant.name %></td>
        <td><%= variant.stock %></td>
        
        <td>
            <% if(variant.stock.positive?) %>
                <%= text_field_tag (:email), nil, placeholder: 'Email',class:'form-control' %>
            <% end %>
        </td>
        <td>
        <% if(variant.stock.positive? && user_signed_in?) %>
            <%= button_to  "Send Gift", nil, class: 'btn btn-info btn-sm'  %>
        <% else%>
            <%= link_to  "Not aviable", "#", class: 'btn btn-danger btn-sm' %>
        <% end %>
        </td>
    </tr>
    <% end %>
<% end %>